### ISSUE TITLE
Cambios para a rama mysql

### ISSUE THREAD

**Issue by alambike** [RIYIC/app_owncloud#1]
Na receta de deploy.rb
- Poñer o autoconfig que hai na rama master, e quitar o config que do magento ( e recuperar a template)
- Agregar ao array de extra_packages os 2 paquetes que falta da antiga deploy

```
    php5-json 
    smbclient
```
- Nas opcions do php_ini, o máis importante e o subir os  parametros do tamaño de 'upload' como estaba no receta de  deploy vella:

```
    php_ini_admin_values  "upload_max_filesize" => app['max_upload_size'],
                          "post_max_size" => app['max_upload_size']
```

E deixar o valor por defecto que había en attributes.rb
`default['app']['owncloud']['max_upload_size'] = '512M'`
- No attributes.rb o parámetro default_system_lang non se usa, quitalo porque debía ser do magento
  `default['app']['owncloud']['default_system_lang'] = 'es_ES'`

Polo demais ok

**Comment by alambike** [comment]
Agregeille a execución do script de inicialización, e correxín un par de cousas. Ver https://github.com/RIYIC/app_owncloud/pull/2
Xa está no paquete de cookbooks para probar

**Comment by juair10** [comment]
Ok

Enviado desde mi iPhone

**Comment by alambike** [comment]
mergeado
